### ISSUE TITLE
lab2

### ISSUE THREAD

**Issue by StNikolay** [StNikolay/lab2#1]
@evgeny-p

**Comment by evgeny-p** [comment]
Весь код по левому краю, значит, дальше можно не смотреть.

Определитесь с соглашениями о кодировании (ссылки на некоторые были даны на первом занятии) и придерживайтесь их.

**Comment by StNikolay** [comment]
Табуляция сделана.
Потому что мы живем вместе и имеем один компьютер на двоих.

**Comment by evgeny-p** [comment]
Параметры `user.name` и `user.email` могут быть установлены как глобально, так и локально для рабочей копии репозитория.

Соглашения о кодировании — это не только отступы.

1. Неконсистентное именование переменных. Некоторые названы в верхнем регистре, некоторые в нижнем.
1. После запятых должен ставиться пробел.
1. Зачем строки 9−16 выделены в блок как отступами, так и фигурными скобками?
1. Строку 14 лучше разделить на две.
1. `return 0` в строке 15 выполняется безусловно, весь последующий код недостижим.

**Comment by StNikolay** [comment]
исправлено
разве где-то не стоят пробелы после запятых?

**Comment by evgeny-p** [comment]
Принято.

В последующих работах:

1. Нужно выбрать соглашения о кодировании и придерживаться их.
1. Первая часть работы была выполнена в отдельной ветке, с мержем. А исправления вносились напрямую в мастер. Выполнение любой задачи начинается с создания ветки. В мастере не должно быть промежуточных версий с незавершенной работой.
